### ISSUE TITLE
`Raster.reproject()` sometimes warns in a weird way

### ISSUE THREAD

**Issue by erikmannerfelt** [GlacioHack/GeoUtils#220]
**Describe the bug**
When a `Raster` is loaded without a nodata value, `Raster.reproject` will almost 100% trigger a warning about it.
This is not fundamentally wrong, but I feel like the warning is kind of in the wrong place..

**To Reproduce**
```python
>>> import geoutils as gu
>>> img = gu.Raster(gu.datasets.get_path("landsat_B4_crop"))
>>> _ = img.reproject(dst_res=20)
/home/erik/Projects/ETH/GeoUtils/geoutils/georaster.py:827: UserWarning: No nodata set, will use 0
  warnings.warn("No nodata set, will use 0")
```

**Expected behavior**
I don't know exactly what the expected behavior would be, but this particular example feels wrong! Some ideas of solutions are:

- Set the nodata when loading the raster. Maybe this will have unforeseen consequences, however?
- Somehow separate these two scenarios: "There is no nodata-value" or "There may or may not be a nodata-value, but it doesn't exist for now".
- Allow no nodata value in `Raster.reproject()` (I think I prefer this one actually)

**System (please complete the following information):**
 - OS: linux
 - Environment: latest dev environment.

Thoughts, @adehecq @atedstone ?

**Comment by adehecq** [comment]
The issue is particularly problematic with Byte data. With this data type, it's difficult to set a no data value for default as most values are used (0 could be a relevant value).
Initially, if no nodata value was set, it was set to None, and rasterio was taking care of setting it to default. According to what I wrote [here](https://github.com/GlacioHack/GeoUtils/blob/12bd607fe8024720ff264545abf0cc5ba0156ea6/geoutils/georaster.py#L850), it is set to 99999 by default, which has unexpected results for Byte dtype. Hence, I decided to set it to 0 and raise a warning, because this may have unexpected consequences.

The nodata value could indeed be an argument of reproject, but the issue will still be the same. If using a Byte image and choosing a default value may have unexpected consequences, so I think a warning is still the safest way.
The ideal solution would be to handle values and mask separately so that the nodata does not take up one value. But I don't know if it's possible to do. Rasterio has another way to handle no data masks that could be investigated more: https://rasterio.readthedocs.io/en/latest/topics/masks.html.
Sorry I don't have an easy solution to provide right now.

**Comment by erikmannerfelt** [comment]
What would be the consequences of simply allowing `None` as nodata? That would more or less solve the problem, right?

**Comment by adehecq** [comment]
That's what was done before, but as I just said, the default nodata is then set by rasterio. My experience was that the result was unexpected with Byte data, but reading the rasterio documentation again, it says the default nodata is 0, which would be the same...
Anyway, one thing I could do possibly, is to check whether the no data value set is used in the source raster, and raise a warning only in that case. Would that help?
It should not raise a warning with the Landsat test case, since it does not contain any 0 value, except for the cropped set. Actually, in that case, there should be a nodata value!

**Comment by erikmannerfelt** [comment]
You are more involved in the problems here! Perhaps the suggestion you provide would work?

The optimal case is if we have tests that validate when and how GeoUtils should warn. Then we can just cherry-pick the actual implementation to make the tests pass.
