### ISSUE TITLE
`Raster.show()` does not respect the current axis.

### ISSUE THREAD

**Issue by erikmannerfelt** [GlacioHack/geoutils#241]
**Describe the bug**
The `Raster.show()` method does not care about subplots, and also calls `plt.show()` which messes up any attempt to fix it! The easy solution is to add the `ax` keyword, but it is odd that `ax` does not default to `plt.gca()`. 

**To Reproduce**
```python
import matplotlib.pyplot as plt
import geoutils as gu

img1 = gu.Raster(gu.datasets.get_path("landsat_B4"))
img2 = img1 + 10


plt.subplot(121)
img1.show()
plt.subplot(122)
img2.show()

plt.show()
```

This is how to make it work correctly, but it is not easy for newcomers to understand why:
```python
import matplotlib.pyplot as plt
import geoutils as gu

img1 = gu.Raster(gu.datasets.get_path("landsat_B4"))
img2 = img1 + 10


ax0 = plt.subplot(121)
img1.show(ax=ax0)
ax1 = plt.subplot(122)
img2.show(ax=ax1)

plt.show()
```

**Expected behavior**
One figure with two subplots should be created. This currently shows four plots; two empty subplots and two single raster plots.

**Comment by adehecq** [comment]
You're right, it's not ideal. Should we just copy the behavior of rasterio? Which is:
- if no ax is provided, use plt.gca() and is followed by plt.show()
- otherwise, use provided ax and does not call plt.show()

https://github.com/mapbox/rasterio/blob/3910956d6cfadd55ea085dd60790246c167967cd/rasterio/plot.py#L130

I like that plt.show() is called when no argument is given to img.show() so that one get a view of the raster in one line. But I think that would still prevent your first example unfortunately...

For info, it seems like geopandas also completely ignore the current axes too (so we can do better! 😉):
```
vect = gu.Vector(gu.datasets.get_path("glacier_outlines"))
plt.subplot(121)
vect.ds.plot()
plt.subplot(122)
vect.ds.plot()
plt.show()
```
