### ISSUE TITLE
Issue with setuptools_scm[toml] in requirements.txt

### ISSUE THREAD

**Issue by adehecq** [GlacioHack/geoutils#415]
I'm building a repository that has geoutils in its dependencies. I created a new conda environment with geoutils installed, which worked fine. Then to setup my repository, I ran `pip install -e . --no-deps` and it fails with the following error:
"pkg_resources.DistributionNotFound: The 'setuptools-scm[toml]>=6.2' distribution was not found and is required by geoutils"

Indeed, the dependence to setuptools is clear in the requirements.txt but not mentioned in the environment.yml. Is this normal?
An easy fix is of course to install without the option `--no-deps`, but I would expect the conda install to provide all necessary dependencies.

Below are samples from my own environment.yml and setup.py:
environment.yml:

> channels:
>   - conda-forge
> dependencies:
>   - python=3.11
>   - ipython
>   - numpy
>   - matplotlib
>   - scipy
>   - gdal
>   - scikit-image
>   - opencv
>   - pandas
>   - shapely
>   - geopandas
>   - packaging
>   - psutil
>   - seaborn
>   - geoutils
>   - rasterio
>   - tqdm

setup.py:

>     install_requires=[
>         "numpy",
>         "matplotlib",
>         "scipy",
>         "gdal",
>         "scikit-image",
>         "pandas",
>         "shapely",
>         "geopandas",
>         "packaging",
>         "psutil",
>         "seaborn",
>         "geoutils",
>         "rasterio",
>         "tqdm",
>     ],
>

**Comment by rhugonnet** [comment]
The issue here is because there are two types of dependencies (I got familiar with that when I recently updated our pip/conda maintenance):
- Setup dependencies (for installing your package),
- Package dependencies (to add functionalities to your code).

Setup dependencies are defined in the `pyproject.toml` (previously in the `setup.py`): https://github.com/GlacioHack/geoutils/blob/main/pyproject.toml#L1, and not installed via `environment.yml` or `requirements.txt`.

In your case, I think you can fix your issue by running `pip install -e .` (without the `--no-deps` that is not advised for installing a package: already installed dependencies of your package shouldn't be overwritten, pip will just install what's missing after your environment was installed, so the Setup dependencies).
Normally that should take care of the rest for you!

**Comment by adehecq** [comment]
Thanks for the explanation!
Alright, I'll just run without the `--no-deps` option. I prefer to use that option first to ensure that I have installed all required dependencies with conda. Mixing conda and pip install can makes things more difficult to handle later, but here as you say it's a setup dependency.
