### ISSUE TITLE
Replace names `size` and `indexes`

### ISSUE THREAD

**Issue by adehecq** [GlacioHack/geoutils#449]
+1 for `grid_size` and for `bands`!

_Originally posted by @rhugonnet in https://github.com/GlacioHack/geoutils/issues/440#issuecomment-1904244023_
            
Following #440, it was decided to rename `size` (in reproject and proximity) by `grid_size` and `indexes` (in load and split_bands) by `bands`, therefore completely reverting back what was done in previous PRs. 🤦‍♂️

**Comment by rhugonnet** [comment]
The new aspects being:
- The argument names `grid_size`, `size` and `dst_size` were all used before, recently changed to `size`, so we're making it all consistent but also clearer with `grid_size` because `size` is such a common Python name,
- We would only replace `indexes` into `bands` for the argument names of the two functions mentioned above, and not for internal (non-public) variables, to stay consistent with Rasterio internally. 

If that's what you also had in mind.
So we're not completely reverting! :stuck_out_tongue_winking_eye:

**Comment by adehecq** [comment]
You're right, I was a bit exaggerating with the term "completely reverting" ! I could not find a funny way to describe our indecision 😉
