### ISSUE TITLE
Raster - support to instantiate a raster directly from an Xarray object

### ISSUE THREAD

**Issue by geograFie** [GlacioHack/geoutils#519]
Awesome utility! I am using it in combination with xDEM. 

However, it would be great if there was support for `xr.DataArray` object type in `Raster.from_array()`. I want to be able to directly convert from Xarray to Raster without having to store and read from a file or performing other conversions. 

Currently, I solved this by reading the data and `Affine` transformation using `rio` from my `xr.DataArray`:
```python
dem = xr.DataArray(...)
crs = CRS.from_wkt(dem['spatial_ref'].attrs['crs_wkt'])
epsg = crs.to_epsg()
affine = dem.rio.transform()

raster = gu.Raster.from_array(
    data=dem.data,
    transform=affine,
    crs=epsg
)

x_dem = xdem.DEM(raster)
```

It would be nice to have something like this instead:
```python
dem = xr.DataArray(...)

raster = gu.Raster.from_array(dem)
OR  
raster = gu.Raster.from_xarray(dem)

x_dem = xdem.DEM(raster)
```

**Comment by rhugonnet** [comment]
Thanks for opening this @geograFie! 

You're right, we need to add a `from_xarray()` function, it's not the first time we get that request! I'll move this to a higher priority so that it is available in the next release :slightly_smiling_face:.

We are also writing an Xarray accessor mirroring the Raster/DEM APIs, so soon you'll be able to call any GeoUtils/xDEM function from your Xarray object directly!
For instance:
```python
ds = xr.DataArray(...)

prox = ds.gu.proximity()
curv = ds.dem.curvature()
```

Hopefully we'll be done by the end of summer. The accessor names will likely be `gu` and `dem`! See #383 and https://github.com/GlacioHack/xdem/issues/392.

**Comment by geograFie** [comment]
**Perfect!** 

Thanks for the fast response
